#!/usr/bin/perl -w
use strict;
use Date::Calc qw(Calendar);
#usage perl perldate3 monthnum  year; 
#perl perldate3 8 2002 for AUG2002
#defaults to current month


my $month = shift || (localtime(time))[4]+1; #numeric for subroutine

my $year = shift || (localtime(time))[5]+1900;

my @cal = parseCalendar();

my @months = (undef,'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul','Aug', 'Sep', 'Oct', 'Nov', 'Dec');
$month = $months[$month]; #change $month to 3-letter abbreviation

print "\n$month\-$year: ",'Mo  Tu  We  Th  Fr  Sa  Su',"\n"; 
my $i = 1;


foreach my $cal_line (@cal)
{
print "Week - ",$i++,": ";
foreach my $day (@$cal_line)
{
 $day ||= "  ";
 print "$day  ";
}
 print "\n";
}
print "\n";
exit;

#####################################################################

sub parseCalendar
{
 my $cal = Calendar($year, $month);
 my @cal = split(/\n/, $cal);
 splice(@cal, 0, 3); # get rid of the first three lines (don't need em)+;
 my @rv = map{$_ = substr($_, 1, length);[split /\s{4}|\s{2}/];}@cal;
 return @rv;
}

#####################################################################
# Output default
#bash-4.4$ perl perldate3
#
#Mar-2018: Mo  Tu  We  Th  Fr  Sa  Su
#Week - 1:              1   2   3   4  
#Week - 2:  5   6   7   8   9  10  11  
#Week - 3: 12  13  14  15  16  17  18  
#Week - 4: 19  20  21  22  23  24  25  
#Week - 5: 26  27  28  29  30  31
#####################################################################
# Output input user
#bash-4.4$ perl perldate3 2 2012
#
#Feb-2012: Mo  Tu  We  Th  Fr  Sa  Su
#Week - 1:          1   2   3   4   5  
#Week - 2:  6   7   8   9  10  11  12  
#Week - 3: 13  14  15  16  17  18  19  
#Week - 4: 20  21  22  23  24  25  26  
#Week - 5: 27  28  29
#####################################################################