#!/usr/bin/env perl
use strict;
use warnings;
use Time::Local;

my @names = qw/ January February March April May June July August September October November December/;

my $year = shift ||'2013';

for my $month (0..11)
{
 print " $names[$month] $year\n";
 print calendar($year, $month), "\n\n";
}

sub __isleap
{
 my $ano = $_[0];

 if($ano%400 == 0)
  {
   return 1;
  }
  elsif($ano%4==0 && $ano%100!=0)
  {
   return 1;
  }
  else
  {
   return 0;
  }
}

sub calendar
{
 my ($year, $month) = @_;
 my @mon_days = qw/31 28 31 30 31 30 31 31 30 31 30 31/;
 
 if(__isleap($year))
 {
  $mon_days[1] = 29;
 }
    
 my $cal = " Sun Mon Tue Wed Thu Fri Sat\n";
 
 # Months are indexed beginning at 0
 my $time = timegm(0,0,0,1,$month,$year);
 my $wday = (gmtime $time)[6];
    
 $cal .= "    " x $wday;
    
 my $mday = 1;

 while($mday <= $mon_days[$month])
  {
   $cal .= sprintf "%4s", $mday++;
   $cal .= "\n"
   if($wday + $mday -1) % 7 == 0;
  }
 return $cal;
}